# Generated by Django 4.2.3 on 2023-07-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CADASTRO_BELICO', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carregador_1',
            options={'verbose_name': 'Cadastro Carregador_1', 'verbose_name_plural': 'Cadastro Carregadores_1'},
        ),
        migrations.AlterModelOptions(
            name='carregador_2',
            options={'verbose_name': 'Cadastro Carregador 2', 'verbose_name_plural': 'Cadastro Carregadores 2'},
        ),
        migrations.AlterModelOptions(
            name='carregador_3',
            options={'verbose_name': 'Cadastro Carregador_3', 'verbose_name_plural': 'Cadastro Carregadores_3'},
        ),
    ]
