# Generated by Django 4.2.3 on 2023-07-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CADASTRO_BELICO', '0002_alter_carregador_1_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carregador_1',
            options={'verbose_name': 'Cadastro Carregador 1', 'verbose_name_plural': 'Cadastro Carregadores 1'},
        ),
        migrations.AlterModelOptions(
            name='carregador_3',
            options={'verbose_name': 'Cadastro Carregador 3', 'verbose_name_plural': 'Cadastro Carregadores 3'},
        ),
    ]
