# Generated by Django 4.2.3 on 2023-07-09 18:50

import CADASTRO_POLICIAIS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, validators=[CADASTRO_POLICIAIS.models.validate_matricula], verbose_name='MATRÍCULA')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='NOME DE GUERRA')),
                ('posto_graduacao', models.IntegerField(choices=[(1, 'CEL'), (2, 'TEN CEL'), (3, 'MAJ'), (4, 'CAP'), (5, 'TEN'), (6, 'ASP'), (7, 'SUB TEN'), (8, 'SGT'), (9, 'CB'), (10, 'SD'), (11, 'AL SD')], verbose_name='POSTO/GRADUAÇÃO')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-MAIL')),
                ('nome', models.CharField(max_length=15, verbose_name='NOME COMPLETO')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
            },
        ),
    ]
