# Generated by Django 4.2.3 on 2023-07-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CADASTRO_BELICO', '0003_alter_carregador_1_options_and_more'),
        ('CADASTRO_POLICIAIS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga_Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.IntegerField(choices=[(1, 'CEL'), (2, 'TEN CEL'), (3, 'MAJ'), (4, 'CAP'), (5, 'TEN'), (6, 'ASP'), (7, 'SUB TEN'), (8, 'SGT'), (9, 'CB'), (10, 'SD'), (11, 'AL SD')], verbose_name='POSTO/GRADUAÇÃO')),
                ('nomeguerra', models.CharField(max_length=20, verbose_name='NOME DE GUERRA')),
                ('municao', models.IntegerField(choices=[(1, '.40'), (2, '.556')], verbose_name='MUNiÇÃO')),
                ('observacao', models.CharField(max_length=50, verbose_name='OBSERVAÇÃO')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CADASTRO_BELICO.cadastroarma', verbose_name='ARMA')),
                ('cad_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CADASTRO_POLICIAIS.cadastropolicial', verbose_name='MATRÍCULA')),
                ('carreg1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CADASTRO_BELICO.carregador_1', verbose_name='CARREGADOR 1')),
                ('carreg2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CADASTRO_BELICO.carregador_2', verbose_name='CARREGADOR 2')),
                ('carreg3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CADASTRO_BELICO.carregador_3', verbose_name='CARREGADOR 3')),
                ('e_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CADASTRO_POLICIAIS.user')),
                ('placabalistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CADASTRO_BELICO.cadastrocolete', verbose_name='COLETE')),
            ],
            options={
                'verbose_name': 'Carga_Descarga',
                'verbose_name_plural': 'Cargas_Descargas',
            },
        ),
    ]
